// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrWoNIDkSmzrB3hHEdgKentLnlqZlLDss',
    appId: '1:617565505738:web:6c6cce36852779a8934c33',
    messagingSenderId: '617565505738',
    projectId: 'saferun-a1ccc',
    authDomain: 'saferun-a1ccc.firebaseapp.com',
    storageBucket: 'saferun-a1ccc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsC1fTZc3D6nFtK8SdVxVVfnTMIwDBuhg',
    appId: '1:617565505738:android:43ab99503420f30a934c33',
    messagingSenderId: '617565505738',
    projectId: 'saferun-a1ccc',
    storageBucket: 'saferun-a1ccc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcJCRxgmZ0v0EnDT6UpOA2i7ayEisYj20',
    appId: '1:617565505738:ios:9bf18cbe0810efa5934c33',
    messagingSenderId: '617565505738',
    projectId: 'saferun-a1ccc',
    storageBucket: 'saferun-a1ccc.firebasestorage.app',
    iosBundleId: 'com.example.saferun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcJCRxgmZ0v0EnDT6UpOA2i7ayEisYj20',
    appId: '1:617565505738:ios:9bf18cbe0810efa5934c33',
    messagingSenderId: '617565505738',
    projectId: 'saferun-a1ccc',
    storageBucket: 'saferun-a1ccc.firebasestorage.app',
    iosBundleId: 'com.example.saferun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrWoNIDkSmzrB3hHEdgKentLnlqZlLDss',
    appId: '1:617565505738:web:ac9b756e531763b6934c33',
    messagingSenderId: '617565505738',
    projectId: 'saferun-a1ccc',
    authDomain: 'saferun-a1ccc.firebaseapp.com',
    storageBucket: 'saferun-a1ccc.firebasestorage.app',
  );
}
